### ISSUE TITLE
Investigate switching away from ginkgo/gomega

### ISSUE THREAD

**Issue by mitchnielsen** [PrefectHQ/prefect-operator#38]
## Summary

Context: https://github.com/PrefectHQ/prefect-operator/pull/34#discussion_r1722360958

> although ginkgo/gomega are included in the scaffolding, it became a bit of a burden over time because it required learning a bespoke testing framework (which is quite complex, as you can tell from [their docs](https://onsi.github.io/ginkgo/)). I think this is completely fine for now, but there are complexities here that eventually made us wish we had just used Golang's build in testing package, or at most stretchr/testify for simple assert statements. That would have felt much more Go-native, eliminated weird Ginkgo-specific failures, and made it easier for community members to contribute.

Let's try to get to this sooner than later as it'll only be harder to replace down the road.

## Resources
- https://github.com/stretchr/testify
- https://pkg.go.dev/testing

## Acceptance criteria

- [ ] Open a PR to demonstrate what it would look like to replace `ginkgo`/`gomega`
- [ ] If we like how that goes, open an issue to track replacing the rest of the instances

**Comment by chrisguidry** [comment]
Cancelling this for now, we can revisit in the future, but Ginkgo is the default for the scaffolding we're using
